### ISSUE TITLE
configure

### ISSUE THREAD

**Issue by rabbitear** [niklata/ndyndns#6]
Usually I'd use ./autogen.sh to create the ./configure, but that doesn't exist in this project.  Is there another way to create the ./confugure file?

**Comment by niklata** [comment]
Assuming you have autotools installed (if you don't, then just install it from your distro's package management tool), just run `autoconf` from the ndyndns source directory.  It should create a fresh configure that is generated from the configure.in file that is in the ndyndns repo.  Then you can carry on with the directions in the README.
